import { 
    GET_SERVICES,
    GET_PROJECTS,
    GET_PROJECTBYID,
    GET_PROJECTSBYSLUG,
    GET_LATESTPROJECTS
} from './queries';

export {
    GET_SERVICES,
    GET_PROJECTS,
    GET_PROJECTBYID,
    GET_PROJECTSBYSLUG,
    GET_LATESTPROJECTS
};